### ISSUE TITLE
Compilation fails in VS17

### ISSUE THREAD

**Issue by JayhawkZombie** [JamesBoer/Jinx#1]
I think it would be important to note that compilation fails in VS17.  Your fix for addressing the VisualStudio 2015 bug almost works for VisualStudio 2017.

On [JxUnicode.cpp:188](https://github.com/JamesBoer/Jinx/blob/master/Source/JxUnicode.cpp#L188), the check should be `#if _MSC_VER >= 1900`.  For VisualStudio 2017 (version 15.5.2) the value for `_MSC_VER` is 1912 and so it doesn't use your fix.  

On a more positive note:   
Your bytecode plays very well with binary serialization, which makes it easy to precompile scripts and ship bytecode instead of source code (and I can package the bytecode in my binary object archives so the bytecode is hidden from the user).

**Comment by JamesBoer** [comment]
Fixed.  Thanks for the report.  The original `#if _MSC_VER == 1900` was intention, as an MSVC dev had reported this particular bug fixed well over two years ago.  As such, I thought it would surely be fixed in VS 2017.  I've changed it to `>=`, a safer option going forward.
