### ISSUE TITLE
Issue using `x key` and `x value` with literal in loop over

### ISSUE THREAD

**Issue by CasparKielwein** [JamesBoer/Jinx#15]
While playing around with the current state of this nice (and excellently documented!) language, I found the following issue:

## Description

Using `x key` and `x value` interleaved with a literal within a single statement in a loop body results in error.
```
'get key' called with non-iterator param
'get value' called with non-iterator param
```

If I remove the literal in the statement it works fine.
E.g. the following works:
```
loop x over numbers
     foo x key, x value
end
```
while
```
loop x over numbers
     foo x key, 1, x value
end
```
does not
If I split the body into multiple statements it works as well.

## Steps to reproduce
* execute the script from the tutorial for `Loop over Collections`
```
set 'my list' to 5, 4, 3, 2, 1
loop x over 'my list'
    write line "key = ", x key, ", value = ", x value
end
```

### Expected  Behavior
The console shows the string "key = 1, value = 5" (...)

### Observed Behavior
The console shows
```
'get key' called with non-iterator param
'get value' called with non-iterator param
nullnull
```

## Affected Versions
* current master (db991c815ddb21e37adfb69e037b36592ad4c2de)

**Comment by JamesBoer** [comment]
Thanks for the detailed bug report.  This should be fixed in v1.2.3
