### ISSUE TITLE
Unable to wait for coroutines to finish inside of functions

### ISSUE THREAD

**Issue by LittleToonCat** [JamesBoer/Jinx#19]
Hi, I'm looking to integrate Jinx as a primary language game-logic wise for my prototype engine due to its cooperative asynchronous like nature, so it's going to involve a lot of function calling, mostly from the C++ side (especially one that's called upon boot-up to initialize and load everything up).

But I have found out that I can not have a calling function wait for another coroutine to finish, while waiting in the script's main body (outside a function) works as intended.  I think it has to do with a script being marked as "finished" after calling `ExecuteScript` before a function could be even called with `CallFunction`.  Especially since a typical script for this planned engine will be nothing but functions and coroutines.

Other languages like JavaScript and Python can await for coroutines to finish inside of functions, but if Jinx couldn't, what's the point?

C++:
```C++
auto script = _runtime->ExecuteScript(file.c_str(), nullptr, "boot.jinx");
    
auto id = script->FindFunction(nullptr, "boot {}");
script->CallFunction(id, {param});

if (script->IsFinished()) {
    TraceLog(LOG_INFO, "How is it finished???");
}
```
boot.jinx:
```
import core

function hello
    loop from 1 to 10
        write line "Hello"
        wait
    end
end

private function boot {integer param}
    -- other stuff...

    set c to async call function hello
    write line "Waiting..."
    wait until c is finished
    -- Lines below will never be reached...
    write line "Finished waiting"
end
```

Output:
```
Hello
Waiting...
Hello
INFO: How is it finished???
````

**Comment by JamesBoer** [comment]
Thanks for the clear description and repro.  I'll look into this.

**Comment by JamesBoer** [comment]
I've added `IScript::CallAsyncFunction()` to the development branch, which returns an object with the `ICoroutine `interface, which is what Jinx uses internally.  This should allow you to either utilize it in an async  manner from code, or block until it's finished executing, whatever is more appropriate.

```
auto script = _runtime->ExecuteScript(file.c_str(), nullptr, "boot.jinx");
    
auto id = script->FindFunction(nullptr, "boot {}");
auto coroutine = script->CallAsyncFunction(id, {param});
while (!coroutine->IsFinished()) {}

TraceLog(LOG_INFO, "It's definitely finished now");

```

Let me know if this solution works for you, and if you have any additional suggestions.

**Comment by LittleToonCat** [comment]
After switching to the development branch and doing some additional testing, this is exactly what I needed.  Thank you very much!
